### ISSUE TITLE
Allow multiple files to be validated for command validate_schema

### ISSUE THREAD

**Issue by svdimchenko** [marcosschroh/dc-avro#68]
**Is your feature request related to a problem? Please describe.**
I'm using this lib in my ci pipeline to validate avro schemas before publishing them to confluent kafka schema registry. The problem is that dc_avro does not support feature to validate multiple schemas at once.

**Describe the solution you'd like**
I'd like to have possibility to pass list of files for validation.

**Describe alternatives you've considered**
I can create my own script to achieve same result but this feature will be rather useful in this lib I guess

**Additional context**
The best option is to add pre-commit usage method for this library.

**Comment by marcosschroh** [comment]
Thanks @svdimchenko . I think it make sense your `feature request`. PR is more than welcome, otherwise I will try to add it asap.

**Comment by svdimchenko** [comment]
@marcosschroh thank you for such great lib. I'll be able to work on it after week or 2. So if you can get it done before, that will be super as well.

**Comment by svdimchenko** [comment]
@marcosschroh kindly review the PR with mentioned feature implementation, we can now use this lib in pre-commit!

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dc-avro/pulls

**Comment by svdimchenko** [comment]
@marcosschroh I've also opened the PR to add your repo to pre-commit hooks if you don't mind https://github.com/pre-commit/pre-commit.com/pull/890

**Comment by marcosschroh** [comment]
Awesome @svdimchenko !!
